### PR TITLE
Rename updated DE tutorial

### PR DESCRIPTION
**Pull request by devmotion**

### CODE REVIEW

**Comment by yebai** [comment]
Thanks, @devmotion, @cpfiffer!

**Comment by devmotion** [comment]
FYI: The webpage is not deployed when one runs the action manually, apparently it requires a push event on the master branch (see https://github.com/TuringLang/Turing.jl/runs/1572810451?check_suite_focus=true#step:6:196)

**Comment by yebai** [comment]
Maybe bump the version number to emulate a push event?

**Comment by devmotion** [comment]
I added an empty commit: https://github.com/TuringLang/Turing.jl/commit/a031b86c8be1980de5490deafca148b8871e98ce

**Comment by devmotion** [comment]
It worked: https://turing.ml/dev/tutorials/10-bayesiandiffeq/

**Pull request merged**
