### PR TITLE
Fix typo in SDE fitting

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
How do you make it spawn a rebuild job?

**Comment by devmotion** [comment]
There is no rebuild job, everything is built manually (and IIRC there is also some delay until it ends up on the website but maybe that changed) 😢

**Comment by ChrisRackauckas** [comment]
Hmm, maybe we should just get you setup with the new SciMLBenchmarks setup.

**Comment by devmotion** [comment]
I guess that maybe even a simpler setup could be sufficient since most tutorials are much less compute intensive than the benchmarks in SciML. In general, the whole jmd setup is still quite new, e.g., Manifest files and a CompatHelper setup are missing (https://github.com/TuringLang/TuringTutorials/issues/116).

**Comment by ChrisRackauckas** [comment]
Being less compute intensive would just mean it would make sense to use a different queue, i.e. use the non-exclusive AMDCI

**Comment by devmotion** [comment]
It would be great if it is possible to use the same setup as in SciMLBenchmarks, I just assumed the benchmarks run on some private workstations and clusters and it might be easier with some simple CI setup initially.

**Comment by ChrisRackauckas** [comment]
It just uses the Julialang Buildkite which we have a ton of extra servers on there for long jobs. @staticfloat we need to get SciMLTutorials and FluxBench using it too, so we should talk about how to start distributing this around the ecosystem.

**Pull request merged**
