### PR TITLE
Added variational inference and differential equations markdown

### PR DESCRIPTION
**Pull request by torfjelde**
Final markdown generated for the tutorials generated.

### CODE REVIEW

**Comment by devmotion** [comment]
This seems to be the outdated first iteration of the diffeq tutorial? The most recent version should contain sections about missing data and DDEs as well: https://turing.ml/dev/tutorials/10-bayesiandiffeq/

**Comment by torfjelde** [comment]
Ah yes, so this is because master has a couple of commits ahead of `jmd-staging`. I think we just gotta apply these by hand at this point.

**Comment by torfjelde** [comment]
But can we get this PR merged and then I'll update the bayes diff eq tutorial in a separate PR.

**Comment by devmotion** [comment]
We should just be careful with this specific tutorial - when it was updated, it was messed up and incorrectly moved to a different location, and therefore not shown on the webpage. This was discovered at some point and fixed by moving the file back to the old location, but this then invalidated some links in a publication, so it was fixed by copying it back to the other location (there's sn issue about it). So currently two (hopefully equivalent) files exist in the repo.

**Comment by torfjelde** [comment]
Can you use symlinks? Does that work?

**Comment by devmotion** [comment]
Certainly relative symlinks would work in the repo but I am not sure if the script for building the webpage can deal with symlinks. However, I think it might be better to just remote the duplicate (i.e. "10_diffeq") again - in the [issue](https://github.com/TuringLang/TuringTutorials/issues/96) Chris mentioned that it could be removed after a month or so.

**Comment by torfjelde** [comment]
If `open` follows symlinks (which I would presume it does?), then I think this would actually work very nicely. With the new branch which is compatible with the new TuringTutorials, it will walk TuringTutorials, open file, read, and then write to new file. I do this to circumvent permission issues. As a result, TuringTutorials could simply contain a symlink and the resulting structure in the website would be an "materialized" version of the link.

**Comment by torfjelde** [comment]
But I still think it should be done server-side rather than in TuringTutorials, e.g. using https://github.com/jekyll/jekyll-redirect-from. 
And regarding having a link to the repository (ref the issue above), wouldn't this be fixed by simly linking to a specific commit?

**Comment by torfjelde** [comment]
https://github.com/TuringLang/TuringTutorials/issues/110

**Comment by devmotion** [comment]
I don't know, I still think that 10_diffeq.ipynb should just be deleted as it was requested to be up for only a month in December. But I assume redirects are needed anyway to not break links to the webpage after the transition to the new format?

**Comment by torfjelde** [comment]
Yeah exactly: delete file because >1 month but need redirects for the website due to changing the naming for the new format (also because we're for sure going to do renaming, etc. in the future, so just having a way to redirect is nice as this ensures that linking to the website is always consistent).

**Pull request merged**
