### PR TITLE
Rerun tutorials

### PR DESCRIPTION
**Pull request by cpfiffer**
Reruns some of the tutorials that didn't quite run correctly in #113. I forgot to check in the `Manifest.toml` files as recommended in #116, but I will likely follow up later with a suite of Manifest files.

### CODE REVIEW

**Comment by devmotion** [comment]
Just checked the tutorial at the top and it seems it errors: https://refined-github-html-preview.kidonng.workers.dev/TuringLang/TuringTutorials/raw/jmd-staging/html/03-bayesian-neural-network/03_bayesian-neural-network.html I assume this can be fixed by removing `reshape` for the bias vectors in the definition of `unpack`.

**Comment by cpfiffer** [comment]
Okay, should be fixed now.

**Comment by devmotion** [comment]
You didn't regenerate the HTML file, it seems?

**Comment by cpfiffer** [comment]
Woops, forgot to push it.

**Comment by cpfiffer** [comment]
Okie dokie, fixed the merge issues. I'll push this now.

**Pull request merged**
