### PR TITLE
[WIP] Add supervised learning tutorial

### PR DESCRIPTION
**Pull request by ayan-b**
- [X] Data
- [X] Model
- [ ] Inference
- [ ] Criticism

### CODE REVIEW

**Comment by ayan-b** [comment]
I am trying to port [this](https://github.com/blei-lab/edward/blob/master/notebooks/supervised_regression.ipynb) tutorial. 
@cpfiffer can you please tell me if I am in right direction? :smile:

**Comment by cpfiffer** [comment]
I was just sitting down to look at this, would you still like me to?

**Comment by cpfiffer** [comment]
As a side note, we currently have a linear regression tutorial [here](https://github.com/TuringLang/TuringTutorials/blob/master/5_LinearRegression.ipynb).

**Comment by ayan-b** [comment]
@cpfiffer I was unable to understand how can I get a batch of scalar valued normals (similar to [this](https://www.tensorflow.org/api_docs/python/tf/distributions/Normal)). So, I have decided to study julia and all the essential packages thoroughly first and then resuming writing this tutorial.

**Pull request closed without merging**
