### PR TITLE
infinite MM tutorial

### PR DESCRIPTION
**Pull request by trappmartin**
This tutorial explains the use of the CRP in Turing.

### CODE REVIEW

**Comment by trappmartin** [comment]
Ready to be reviewed.

@cpfiffer: should I add links to the figures and animations? What is the approach for this now?

**Comment by cpfiffer** [comment]
I have only been adding links to animations, since they tend to get lost in translation when the notebook is converted to markdown. If it's just a regular image or plot, you can let them plot as normal.

**Comment by cpfiffer** [comment]
Actually, I'll experiment and see if I can't get the gifs in there without linking anything.

**Comment by trappmartin** [comment]
Awesome, let me know if I will need to change something regarding the image. I'm also happy for any kind of feedback regarding the content of the tutorial.

**Comment by cpfiffer** [comment]
I really like it. I've made a couple minor changes on grammar and stuff, and tidied up the latex so it works better on the site. You can see it in the commit I pushed. I'm not quite done yet formatting the math, because there's some funkiness with the `\begin{align}` stuff that needs work in the weaving script. I'll get to it a bit more tomorrow.

**Comment by cpfiffer** [comment]
I had to remove the `? DirichletProcess` line at the end of the notebook since Weave throws all kinds of errors with that. I pasted in the docstring from the source code instead.

**Comment by trappmartin** [comment]
Thanks!

**Comment by cpfiffer** [comment]
Cool, looks good to me! Fantastic tutorial. I'll let you look over my changes if you like before I merge this over.

**Pull request merged**
