### PR TITLE
Use concurrency group for deployment

### PR DESCRIPTION
**Pull request by devmotion**
It seems this could be useful for us as well if we merge multiple PRs: https://github.com/SciML/SciMLBenchmarks.jl/pull/454

### CODE REVIEW

**Comment by devmotion** [comment]
@staticfloat Do you think that's a good idea?

**Review by staticfloat — APPROVED** [review]

**Comment by staticfloat** [comment]
Yes. It needs a resign of the hashes, I’ll do that later, once I’m at the computer

**Comment by devmotion** [comment]
Just a small reminder @staticfloat, in case you have access to your computer.

**Comment by devmotion** [comment]
Thank you!

**Pull request merged**
