### PR TITLE
Rename and reorder tutorials

### PR DESCRIPTION
**Pull request by ParadaCarleton**

### CODE REVIEW

**Comment by ParadaCarleton** [comment]
@cpfiffer not sure what's off; looks like renaming the folders broke something?

**Comment by devmotion** [comment]
I am not sure didn't we discuss some potential renaming (in a different way and for a different reason?) in the refactoring PR? With some folder  Is that already fixed? Also it seems the names of the folders and files (already on master) are a bit redundant and inconsistent - we have a `NN_name.jmd` file in a `NN-name` folder. Maybe this could be simplified?

**Comment by rikhuijzer** [comment]
The failing tests are my bad and I'm looking into it.

Nice find for the `redirect_from`. However, if I'm not mistaken the syntax should probably be like the example in the [jekyll-redirect-from docs](https://github.com/jekyll/jekyll-redirect-from):
```
title: My amazing post
redirect_from:
  - /post/123456789/
  - /post/123456789/my-amazing-post/
```

**Comment by ParadaCarleton** [comment]
@rikhuijzer uhh, hmm, looks like the tests failed again and I'm not sure why?

**Comment by rikhuijzer** [comment]
> @rikhuijzer uhh, hmm, looks like the tests failed again and I'm not sure why?

Because there are errors, that is, the logs for the tutorials contain "ERROR" a few times. The first two are for tests, but the last ones are for tutorials. This is checked by

https://github.com/TuringLang/TuringTutorials/blob/17d665dd1bc51e50547f495f0ef28fdfcf5cecdb/src/build.jl#L2-L10

You can debug locally and see what the error is by running
```
using TuringTutorials

build_and_exit(changed_tutorials())
```

**Comment by yebai** [comment]
Closed in favour of https://github.com/TuringLang/TuringTutorials/pull/280

**Pull request closed without merging**
