### PR TITLE
Regenerate Manifest.toml with Julia 1.9.2

### LINKED ISSUE #378: Reproducibility between Julia < 1.7 and >= 1.7
The default RNG has changed since Julia 1.7 (https://docs.julialang.org/en/v1.7-dev/NEWS/#Random) and some of notebooks with an explicit RNG (e.g. the Bayesian ODE one) are no longer reproducible as the tutorials are generated using Julia < 1.7. 
Is there a way we can code the notebook such that we set some RNG globally which works for all Julia versions?

### PR DESCRIPTION
**Pull request by devmotion**
Update of #379, let's see how many tutorials are (not) broken.

Broken/assertions fail:

- [x] Logistic Regression: Fixed by https://github.com/TuringLang/TuringTutorials/pull/394/commits/c4242604dec1245dbcf12fdc1e28755f3cd8b68d
- [x] Linear regression: Fixed by https://github.com/TuringLang/TuringTutorials/commit/2d64593d459f2fcaf40f0b19199dccc33f8d025a
- [x] Variational inference: Fixed by https://github.com/TuringLang/TuringTutorials/commit/ef59c15c698e216bb8d07a86d09c20b55656a24e
- [x] Gaussian processes: Disabled in #375, so does not matter :stuck_out_tongue: 
- [x] Seasonal time series: Fixed by https://github.com/TuringLang/TuringTutorials/pull/394/commits/33892a8659af4d4fdf53768816c2f07e7e5ce9e5

Fixes #378.

### CODE REVIEW

**Comment by devmotion** [comment]
@torfjelde The PR is almost ready but I won't be able to finish it today. It seems the VI tutorial has to be updated due to the recent changes in Bijectors - if you want, you can have a look what's the issue and push a fix. Otherwise I'll check it tomorrow.

The time series tutorial I have to run locally to see whether it's an actual problem or we just have to adjust the assertion.

Generally, in case https://github.com/JuliaArrays/FillArrays.jl/pull/273 is merged and released soon, it would be nice to wait for it to avoid having to set FillArrays to 1.0.0 in the tutorials explicitly (otherwise Turing will be downgraded if you try to update the Manifest files). This would also allow us to benefit from some fixes and performance improvements in more recent FillArrays versions.

**Comment by torfjelde** [comment]
Awesome! I'll have a look at the Bijectors stuff :+1:

**Comment by devmotion** [comment]
@torfjelde I fixed the VI tutorial, seems to run fine now.

**Comment by devmotion** [comment]
Once you are fine with the changes, @yebai and @torfjelde, we have to update the buildkite hashes *before* merging the PR (currently I have to unblock manually every buildkite run). Actually I can't do that but I'll ping Elliot.

**Review by torfjelde — APPROVED** [review]
Awesome stuff @devmotion :heart:

**Comment by devmotion** [comment]
@staticfloat can you please regenerate the keys? I switched from Julia 1.6 to 1 in this PR since the latest Turing releases don't support Julia < 1.7 🙂

**Comment by devmotion** [comment]
Thank you @staticfloat :slightly_smiling_face:

**Pull request merged**
