### PR TITLE
Add CI

### LINKED ISSUE #74: Typo in the VI tutorial
image

In the second to last paragraph at the bottom, "overestimating" should be "underestimating".

### LINKED ISSUE #101: MLE examples from the guide are failing on Linux
...but seem to work fine on Windows.   Unfortunately, my Linux box is a work machine, so I can't provide a stack trace.  However, I get MehtodError: objects of type Nothing are not callable.

### LINKED ISSUE #116: Add Manifest.toml and CompatHelper
Currently, only the Project.toml files are checked in, it seems. This helps to avoid conflicts between dependencies of different tutorials but it does not ensure reproducibility. It would be easier to rerun and debug the examples if the Manifest.toml would be checked in as well.

Additionally, one could then use CompatHelper to be informed about updated packages (it would be cool if the tutorials would be rebuilt automatically but it is even helpful if this has to be done manually, I think).

### PR DESCRIPTION
**Pull request by rikhuijzer**
This PR sets up CI for building the tutorials. The suggested CI job consists of the following main steps:

1. Build the tutorials* in parallel, see the section **CI output** below for an example of how the CI logs will look. This build takes about 60 to 90 minutes. Hopefully, we can speed this up a bit more in the future which will benefit users and developers. Only when a tutorial run fails, the logs are shown in the CI log. Note that, like with tests, the job fails _after_ running the code and not during.

2. Write the output to a branch called `artifacts`.

To get the output to show up on https://turing.ml, we only need to change 
```
Pkg.develop(url="https://github.com/TuringLang/TuringTutorials")
```
to
```
Pkg.add(url="https://github.com/TuringLang/TuringTutorials", rev="artifacts-")
```
in [turing.ml/make-utils.jl](https://github.com/TuringLang/turing.ml/blob/6a7e075eef36ef344700064718b6fb14333f4bce/make-utils.jl#L1-L2). Note that I haven't removed the artifacts from `TuringTutorials#master`, so we can always switch this line back if the CI job doesn't work for some reason.

\* @cpfiffer told me that tutorial 10 (differential equations) takes ≈10 hours to complete. Therefore, this tutorial has been excluded from CI for now. My hope is that we can speed the tutorial up and add it later.

- Closes #116
- Closes #101
- Closes #74

## Demo

A job has finished in my fork of TuringTutorials: https://github.com/rikhuijzer/TuringTutorials/actions/runs/1040205250.

The output of the run can be inspected at https://github.com/rikhuijzer/TuringTutorials/tree/artifacts-ci. To verify that the CI really updated something, compare https://turing.ml/dev/tutorials/00-introduction/ which shows Julia Version **1.5.3** with [00_introduction.md](https://github.com/rikhuijzer/TuringTutorials/blob/artifacts-ci/markdown/00-introduction/00_introduction.md) which shows Julia Version **1.6.2**.

## A note on tutorial 3

In the run, tutorial 3 (neural networks) was failing on:
```
advi = ADVI(10, 5_000)
q_hat = vi(m, advi, q);
```
with a `BoundsError`. This is a known issue: #59. I've removed the part for now.

## CI output

```
00-introduction: Starting build
05-linear-regression: Starting build
00-introduction: Build took 7.3 minutes and allocated 18.98 GiB:
00-introduction: Writing log to /home/runner/work/TuringTutorials/TuringTutorials/tutorials/00-introduction/weave.log
01-gaussian-mixture-model: Starting build
05-linear-regression: Build took 10.11 minutes and allocated 30.9 GiB:
05-linear-regression: Writing log to /home/runner/work/TuringTutorials/TuringTutorials/tutorials/05-linear-regression/weave.log
06-infinite-mixture-model: Starting build
06-infinite-mixture-model: Build took 4.67 minutes and allocated 19.62 GiB:
06-infinite-mixture-model: Writing log to /home/runner/work/TuringTutorials/TuringTutorials/tutorials/06-infinite-mixture-model/weave.log
07-poisson-regression: Starting build
07-poisson-regression: Build took 5.51 minutes and allocated 25.78 GiB:
07-poisson-regression: Writing log to /home/runner/work/TuringTutorials/TuringTutorials/tutorials/07-poisson-regression/weave.log
08-multionomial-regression: Starting build
08-multionomial-regression: Build took 5.62 minutes and allocated 44.44 GiB:
08-multionomial-regression: Writing log to /home/runner/work/TuringTutorials/TuringTutorials/tutorials/08-multionomial-regression/weave.log
09-variational-inference: Starting build
01-gaussian-mixture-model: Build took 22.5 minutes and allocated 211.85 GiB:
01-gaussian-mixture-model: Writing log to /home/runner/work/TuringTutorials/TuringTutorials/tutorials/01-gaussian-mixture-model/weave.log
02-logistic-regression: Starting build
02-logistic-regression: Build took 7.31 minutes and allocated 25.54 GiB:
02-logistic-regression: Writing log to /home/runner/work/TuringTutorials/TuringTutorials/tutorials/02-logistic-regression/weave.log
03-bayesian-neural-network: Starting build
09-variational-inference: Build took 33.35 minutes and allocated 429.86 GiB:
[...]
```

### CODE REVIEW

**Comment by torfjelde** [comment]
This is **awesome**! Thank you _so_ much @rikhuijzer !

**Comment by torfjelde** [comment]
Btw, should it be
```
Pkg.add(url="https://github.com/TuringLang/TuringTutorials", rev="artifacts")
```
i.e. withouth the hyphen, given that https://github.com/TuringLang/TuringTutorials/blob/05d2e4b67545f042bd49c614d1f1e7705a287688/.github/workflows/CI.yml#L51

Also, in that case, maybe we should just call it `deployed` or something?

**Comment by torfjelde** [comment]
@yebai Can you allow the PR to run GH actions? I don't have the rights.

**Comment by yebai** [comment]
Not sure, I don't see an option to enable GH actions for this PR. Maybe we have to merge the PR first to enable GH actions?

**Comment by yebai** [comment]
Many thanks, @rikhuijzer - I've merged this PR to enable CIs. Please feel free to create a new PR if there is any additional work.

**Comment by rikhuijzer** [comment]
> Btw, should it be
> 
> ```
> Pkg.add(url="https://github.com/TuringLang/TuringTutorials", rev="artifacts")
> ```
> 
> i.e. withouth the hyphen, given that
> 
> https://github.com/TuringLang/TuringTutorials/blob/05d2e4b67545f042bd49c614d1f1e7705a287688/.github/workflows/CI.yml#L51
> 
> Also, in that case, maybe we should just call it `deployed` or something?

Well spotted. The hyphen shouldn't be there. I've updated the first post.

> Many thanks, @rikhuijzer - I've merged this PR to enable CIs. Please feel free to create a new PR if there is any additional work.

Thank you! I'll keep an eye on it and see whether it's all good now

**Comment by rikhuijzer** [comment]
> Also, in that case, maybe we should just call it `deployed` or something?

I agree that `artifacts` is not perfect. I chose it because it's a commonly use term for these kinds of things in [GitHub](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts) and [GitLab](https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html), but I wouldn't mind changing it to `deployed`, `generated` or `built`.

**Comment by rikhuijzer** [comment]
Interestingly, something which worked perfectly fine locally fails after 90 minutes. I'll soon open a PR with a patch.

**Pull request merged**
