### PR TITLE
Move to `jmd` tutorials

### LINKED ISSUE #86: Tutorials are largely outdated
A lot of the tutorials are unfortunately outdated due to recent improvements in MCMCChains, e.g. https://github.com/TuringLang/Turing.jl/issues/1411.

I'm opening an issue here so as to bring attention to the, well, _issue_.

### PR DESCRIPTION
**Pull request by cpfiffer**
Resolves #86 by merging all the stuff @torfjelde has done to get us up and running on .jmd style tutorials. 

The deploy plan here is a little complicated, but I want to merge this stuff first before I go fix the non-tutorial stuff elsewhere -- the tutorials are a bigger issue IMO and I'm fine with having some weird formatting for a couple hours while I figure out the kinks. In general it looks like we have all the right directories and everything, so there shouldn't be any breakage.

### CODE REVIEW

**Comment by cpfiffer** [comment]
Ugh I hate merge conflicts, please ignore me

**Comment by devmotion** [comment]
😮😮

**Comment by cpfiffer** [comment]
Most of that is us losing a ton of boilerplate Jupyter crap.

**Comment by cpfiffer** [comment]
I'm rerunning some of the tutorials on 1.6 just to make sure we're good, then I'll push them to the branch.

**Comment by torfjelde** [comment]
Awesooome! I'm so excited :tada: 

Btw, I made all those changes line-by-line :sunglasses:

**Comment by cpfiffer** [comment]
Only issue left is on the NN tutorial: 

```julia

Error: MethodError: ReverseDiff.TrackedReal{Float64, Float64, ReverseDiff.T
rackedArray{Float64, Float64, 2, Matrix{Float64}, Matrix{Float64}}}(::Forwa
rdDiff.Dual{ForwardDiff.Tag{ReverseDiff.var"#105#107"{DataType, Tuple{}, Va
l{(1,)}}, Float64}, Float64, 1}) is ambiguous. Candidates:
  (T::Type{var"#s31"} where var"#s31"<:Real)(x::ForwardDiff.Dual) in Tracke
r at /home/cameron/.julia/packages/Tracker/YNNTM/src/lib/real.jl:111
  ReverseDiff.TrackedReal{V, D, O}(value) where {V, D, O} in ReverseDiff at
 /home/cameron/.julia/packages/ReverseDiff/iHmB4/src/tracked.jl:56
Possible fix, define
  ReverseDiff.TrackedReal{V, D, O}(::ForwardDiff.Dual) where {V, D, O}
```

I recall this bug at some point, currently digging through stuff to track it down.

**Comment by leachim** [comment]
Hi there, I did some work on the HMM tutorial, to address some issues that have been raised (#114, TuringLang/Turing.jl#1411, TuringLang/Turing.jl#1528, TuringLang/Turing.jl#1302). I saw that you fixed some of it already, but I further updated the example, so it properly converges and I rewrote some of the parts at the end. Is it okay if I open a pull request here, I based it on the jmd-staging branch?

**Comment by cpfiffer** [comment]
> Is it okay if I open a pull request here, I based it on the jmd-staging branch?

Yep, that's correct, thanks!

**Pull request merged**
