### PR TITLE
Add Bayesian differential equations tutorial

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
And just to show off, SDEs and DDEs are in there too, so yay Turing is the first!

@vaibhavdixit02 is going to take it from here.

### CODE REVIEW

**Comment by cpfiffer** [comment]
100% rad, thanks @ChrisRackauckas and @Vaibhavdixit02! Looking forward to this.

**Comment by devmotion** [comment]
You should make sure to use `truncated` instead of `Truncated` (as in https://github.com/SciML/DiffEqBenchmarks.jl/pull/101).

**Comment by ChrisRackauckas** [comment]
<p>Agreed</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>Yup good ideas.</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by devmotion** [comment]
<p>The tests pass since they are marked as broken 😄 But they test estimation of the delay length as well, so maybe we're good without it. Should add some tests without delay length estimation to make sure that's the case.</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p>It fails here with "<code>p = (α,β,γ,δ)</code>&nbsp;instead of&nbsp;<code>p = [α,β,γ,δ]</code>&nbsp;" change</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p><code>solve</code>  is not compatible with the tuple, <code>concrete_solve</code>   is needed for it to work, so I think to maintain consistency it's better to to stick to array throughout?</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>yeah, adjoints need arrays, so it's best to just use arrays for now.</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<blockquote>introduce history function&nbsp;<code>h</code>&nbsp;in a separate step and first write it just as a function of&nbsp;<code>x</code>&nbsp;and <code>y</code></blockquote><p>I didn't get this completely, can you write out what you mean</p><p> </p><p>The current version is</p><p> </p><p>$\frac{dx(t)}{dt} = \alpha*h(\alpha,\beta,\gamma,\delta,t-1) - \beta*x*y$</p><p> </p><p>$\frac{dy(t)}{dt} = \delta*x*y - \gamma*y$</p><p> </p><p>$h(\alpha,\beta,\gamma,\delta,t) = [1,1] $ </p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>"h" isn't a thing. "h" is actually just the history here. In psuedo-tex, it's </p><p> </p><p>dxdt = \alpha x(t-1) - \beta x y</p><p> </p><p>There's no reason to ever write "h" in the LaTeX</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by devmotion** [comment]
<p>Yeah, I was wondering if that would be a problem. Would be nice to support tuples but I guess then it's best to use arrays for now.</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>FWIW, training in DiffEqFlux seems to work, so I don't know what's going on in those AD tests but we should definitely get it figured out.</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p>This is pretty slow, 14 minutes for 100 iterations. It needs to run for much more but it's so slow?  </p><p> </p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p>18 minutes for 100 iterations..</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p>21 minutes, I was asking because of this the neuralsde channel the other day. Can we use adjoints here instead or is that not done yet?</p><p> </p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p>Ah I see, okay</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by devmotion** [comment]
<p>Shouldn't it be just <code>σ</code>  instead of <code>σ[1]</code> ? </p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>Adjoints would be slower here. It's just an inherently computationally difficult thing.</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by devmotion** [comment]
<p>You should be able to gain a speed up by using multiple threads and writing <code>Threads.@threads for i in 1:length(predictions</code> but it shouldn't be that slow, so it's not really a proper fix.  </p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>yes</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>it should be σ. ReverseDiff should be much slower than ForwardDiff through the solver, but not that much slower? Are you on master? Add a print statement to make sure it's using the InterpolatingAdjoint</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>Recent DiffEqBase release added this (mostly for this tutorial)</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by devmotion** [comment]
<p>BTW you don't use <code>T</code>  anywhere, so you can just get rid of the input argument.</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p>1000? Yeah, I'll leave it overnight now :) </p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p>I hadn't paid attention to the estimate lol</p><p> </p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>Are there plots of the coefficients, chains, and the fits to go along with the results?</p>

**Comment by devmotion** [comment]
<p>I was wondering the same... It seems the chain gets stuck since all proposals are rejected (basically all samples after iteration 8000 it seems).</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by devmotion** [comment]
<p>A quick inspection reveals many type inference problems:</p><pre class="ql-syntax" spellcheck="false">varinfo = Turing.VarInfo(model)
spl = Turing.SampleFromPrior()

@code_warntype model.f(Random.GLOBAL_RNG, model, varinfo, spl, Turing.DefaultContext())
</pre><p> </p><p>In particular, the type of <code>prob</code>  can't be inferred (also not for the other models above), and the solution types are unknown as well, leading to the problem that not even <code>length(predictions)</code>  is inferred as <code>Int</code>.  A possible fix (maybe there's a better one), is to pass <code>prob</code>   as input to the model and use <code>remake</code> . Then the type of the SDE problem is inferred, but the types of <code>predictions</code>   etc are still unknown (it seems there are some inference problems in the ODE and SDE solvers?). The problem of <code>length(predictions)</code>  can be avoided by obtaining it from <code>data</code>  instead (BTW intuitively it doesn't seem helpful to extract the columns and hence allocate (also in the other models) in every run, but I couldn't notice a significant speed-up by using the DiffEqArray directly). Similar to the implementation in DiffEqBayes one should make sure though that SDE solver actually returns a correct, i.e., complete, solution (maybe it could be useful to specify <code>maxiters</code>  as well to avoid excessively long simulations).</p><p>But yeah, also here the problem seems to be that even if you manage to sample that the chains are completely stuck. Did it improve at all with more samples?</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by devmotion** [comment]
<p>BTW I tried Gibbs sampling with MH</p><p><code>chain = sample(model, Gibbs(MH(:σ), MH(:α), MH(:β), MH(:γ), MH(:δ), MH(:ϕ1), MH(:ϕ2)), 1000)</code>  </p><p>and got</p><pre class="ql-syntax" spellcheck="false">Sampling: 100%|█████████████████████████████████████████| Time: 0:05:24
Object of type Chains, with data of type 1000×8×1 Array{Float64,3}

Iterations        = 1:1000
Thinning interval = 1
Chains            = 1
Samples per chain = 1000
internals         = lp
parameters        = α, β, γ, δ, σ, ϕ1, ϕ2

2-element Array{ChainDataFrame,1}

Summary Statistics
  parameters    mean     std  naive_se    mcse      ess   r_hat
  ──────────  ──────  ──────  ────────  ──────  ───────  ──────
           α  1.7659  0.0530    0.0017  0.0134   9.6869  1.1118
           β  1.1488  0.0316    0.0010  0.0086  10.9606  1.0014
           γ  2.9270  0.1047    0.0033  0.0144  70.0644  1.0178
           δ  0.8957  0.0265    0.0008  0.0073   7.2672  1.2330
           σ  0.3335  0.1291    0.0041  0.0283   5.5755  1.0888
          ϕ1  0.3963  0.0859    0.0027  0.0255   4.0161  2.3181
          ϕ2  0.2298  0.0771    0.0024  0.0223   4.0161  1.8136

Quantiles
  parameters    2.5%   25.0%   50.0%   75.0%   97.5%
  ──────────  ──────  ──────  ──────  ──────  ──────
           α  1.6538  1.7449  1.7597  1.8053  1.8669
           β  1.0849  1.1393  1.1393  1.1735  1.1953
           γ  2.7010  2.8738  2.9242  2.9965  3.1636
           δ  0.8485  0.8691  0.9006  0.9138  0.9393
           σ  0.2870  0.2964  0.3053  0.3053  0.6094
          ϕ1  0.2659  0.3201  0.4216  0.4611  0.5142
          ϕ2  0.1128  0.1720  0.1955  0.2876  0.3672
</pre><p>which is not completely great but somewhat close to the true parameter values at least.</p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p>I don't know at this point. It happened with the Turing update to v0.13.0. </p><p> </p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>ehh good enough to ship IMO. Just mention that SDEs are a lot more computationally intensive and so for very good estimates one should run it with more trajectories and more samples</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>This is worth having someone dig into then... that doesn't look good at all.</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ChrisRackauckas** [comment]
<p>Or, how about doing an MAP method and then starting the chains at the MAP?</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Vaibhavdixit02** [comment]
<p>MAP doesn't give me an answer, errors out after a lot of instability warnings.</p>

---

 <a href='https://app.reviewnb.com/TuringLang/TuringTutorials/pull/68/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by devmotion** [comment]
Unrelated to the issues discussed above, when playing around with the draft yesterday I noticed that Manifest.toml should be updated and completed.

**Comment by ChrisRackauckas** [comment]
Thanks @Vaibhavdixit02 for taking it over the finish line. I think it can get continually improved, and the Turing developers might want to look at that issue with the stepsizes, but IMO it's good enough to release.

**Comment by cpfiffer** [comment]
I'm happy to merge -- anyone have further comments? If not, I'll plan on merging tomorrow morning (PST) and getting everything ready to go to get this on turing.ml.

Thanks, you guys! Spectacular work.

**Pull request merged**
